sonar.projectKey=texture-studio-mc
sonar.projectName=texture-studio-mc
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
